### ISSUE TITLE
feature - support atcoder

### ISSUE THREAD

**Issue by sandeshShahapur** [AnanteshG/ContestHub-backend#2]
url: https://atcoder.jp/contests/

i want to add this platform. will work on it soon.
it too like HackerEarth lacks API endpoints, will have to scrape it.

![200w](https://github.com/user-attachments/assets/57bb2aa5-e813-4558-bf14-e6ebcda7616b)

**Comment by AnanteshG** [comment]
Cool. Please go ahead.
